# Generated by Django 3.0.6 on 2020-05-12 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('serie', models.CharField(choices=[('Pré II', 'Pré II'), ('1 Ano', '1 Ano'), ('2 Ano', '2 Ano'), ('3 Ano', '3 Ano'), ('4 Ano', '4 Ano'), ('5 Ano', '5 Ano'), ('6 Ano', '6 Ano'), ('7 Ano', '7 Ano'), ('8 Ano', '8 Ano'), ('9 Ano', '9 Ano'), ('AEE', 'AEE')], default='Pré II', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default='1')),
                ('idioma', models.CharField(choices=[('Português', 'Português'), ('Inglês', 'Inglês'), ('Espanhol', 'Espanhol'), ('Outro', 'Outro')], default='Português', max_length=15)),
                ('codigo', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateField()),
                ('dataDevolucao', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Livro')),
            ],
        ),
    ]
