# Generated by Django 3.0.6 on 2020-05-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200511_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Aluno'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Livro'),
        ),
    ]
