# Generated by Django 3.0.6 on 2020-05-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200524_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='aluno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.CharField(max_length=20),
        ),
    ]
