# Generated by Django 3.0.6 on 2020-07-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_livro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
