# Generated by Django 3.0.10 on 2020-09-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_auto_20200905_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
