# Generated by Django 3.0.10 on 2020-09-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_auto_20200905_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
