# Generated by Django 3.0.6 on 2020-05-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Postdislike',
        ),
        migrations.DeleteModel(
            name='Postlike',
        ),
    ]
